#![doc = include_str!("../README.crate.md")]

pub mod block;
pub mod block_edit;
pub mod core_error;
pub mod document;
pub mod edit;
pub mod errors;
#[cfg(feature = "file")]
pub mod file;
pub mod fingerprint;
pub mod fragment;
pub mod frontmatter;
pub mod index;
pub mod link;
pub mod locate;
pub mod model;
pub mod parser;
pub mod patch;
pub mod protocol;
pub mod read;
pub mod revision;
pub mod search;
pub mod section;
pub mod section_edit;
pub mod stats;
pub mod table;
pub mod target;
pub mod task;
